export const homeListingsData = [
    {"id": "1", "userId": "1","category":"housing","title":"Modern Stylish Home","price":"1,000,000","type":"home","built":"2007","address":"34555 Prove St","city":"San Francisco","state":"CA","zipcode":"9666","seller":"John Chi","email":"johnchi@mail.com","phone":"888-888-0000","description":"Lovely home located in the Bay Area. This home features 5 bathrooms and bedrooms. It has updated kitchen floors and a spacious backyard. Don’t miss this opportunity.","datePosted":"10-25-2021","username":"JohnChi2","image":"housing/image1.jpg","details":{'Type':'House','Heating':'Yes','Cooling':'Yes','Price':'3500','Kitchen':'Yes','Bedrooms':'5','Bathrooms':'5'}},
    {"id": "2", "userId": "1","category":"housing","title":"Minimal Design Home","price":"500,000","type":"home","built":"2010","address":"34555 Down St","city":"San Francisco","state":"CA","zipcode":"9666","seller":"John Chi","email":"johnchi@mail.com","phone":"888-888-0000","description":"Lovely home located in San Francisco.","datePosted":"10-25-2021","username":"JohnChi2","image":"housing/image2.jpg","details":{'Type':'House','Heating':'Yes','Cooling':'Yes','Price/sqt':'3500','Kitchen':'Yes','Bedrooms':'5','Bathrooms':'5'}},
    {"id": "3", "userId": "2","category":"housing", "title":"Small Red House","price":"1,000,000","type":"home","built":"2008","address":"34555 Nile St","city":"San Francisco","state":"CA","zipcode":"9666","seller":"Paul John","email":"pauljohn@mail.com","phone":"888-888-0000","description":"Lovely home located in the Bay Area","datePosted":"10-25-2021","username":"pauljohn3","image":"housing/image3.jpg","details":{'Type':'House','Heating':'Yes','Cooling':'Yes','Pricesqft':'3500','Kitchen':'Yes','Bedrooms':'5','Bathrooms':'5'}},
    {"id": "4", "userId": "2","category":"housing", "title":"Small Red House","price":"1,000,000","type":"home","built":"2008","address":"34555 Nile St","city":"San Francisco","state":"CA","zipcode":"9666","seller":"Paul John","email":"pauljohn@mail.com","phone":"888-888-0000","description":"Lovely home located in the Bay Area","datePosted":"10-25-2021","username":"pauljohn3","image":"housing/image4.jpg","details":{'Type':'House','Heating':'Yes','Cooling':'Yes','Price/sqt':'3500','Kitchen':'Yes','Bedrooms':'5','Bathrooms':'5'}},
    {"id": "5", "userId": "2","category":"housing", "title":"Simple and Clean","price":"1,000,000","type":"home","built":"2011","address":"34555 Purple Ave","city":"San Francisco","state":"CA","zipcode":"9666","seller":"Paul John","email":"pauljohn@mail.com","phone":"888-888-0000","description":"Lovely home located in the Bay Area","datePosted":"10-25-2021","username":"pauljohn3","image":"housing/image5.jpg","details":{'Type':'House','Heating':'Yes','Cooling':'Yes','Price/sqt':'3500','Kitchen':'Yes','Bedrooms':'5','Bathrooms':'5'}},
    {"id": "6", "userId": "3","category":"housing", "title":"Suburban Home","price":"750,000","type":"home","built":"2015","address":"34455 Nice St","city":"San Francisco","state":"CA","zipcode":"9668","seller":"John Cena","email":"johncena@mail.com","phone":"888-888-0000","description":"Lovely home located in the Bay Area","datePosted":"10-25-2021","username":"johncena","image":"housing/image6.jpg","details":{'Type':'House','Heating':'Yes','Cooling':'Yes','Price/sqt':'3500','Kitchen':'Yes','Bedrooms':'5','Bathrooms':'5'}},
]
export const personalListingsData = [];

export const jobsListingsData = [];

export const communityListingsData = [];

export const forSalesListingsData = [];