export const homeListingsData = [
    {"id": "1", "userId": "1","category":"housing","title":"Modern Stylish Home","price":"1,000,000","type":"home","address":"34555 Prove St","city":"San Francisco","state":"CA","zipcode":"9666","seller":"John Chi","email":"johnchi@mail.com","phone":"888-888-0000","description":"Lovely home located in the Bay Area. This home features 5 bathrooms and bedrooms. It has updated kitchen floors and a spacious backyard. Don’t miss this opportunity.","datePosted":"10-25-2021","username":"JohnChi2","image":"housing/image1.jpg",images:['housing/image1.jpg','housing/image9.jpg','housing/image10.jpg'],"details":['Built: 2007','Type : House','Heating: Yes','Cooling : Yes','Price : 3500','Kitchen :Yes','Bedrooms :5','Bathrooms: 5']},
    {"id": "2", "userId": "1","category":"housing","title":"Minimal Design Home","price":"500,000","type":"home","built":"2010","address":"34555 Down St","city":"San Francisco","state":"CA","zipcode":"9666","seller":"John Chi","email":"johnchi@mail.com","phone":"888-888-0000","description":"Lovely home located in San Francisco.","datePosted":"10-25-2021","username":"JohnChi2","image":"housing/image2.jpg",images:['housing/image2.jpg','housing/image7.jpg','housing/image10.jpg'],"details":['built: 2007','Type: House','Heating: Yes','Cooling: Yes','Price/sqt: 3500','Kitchen : Yes','Bedrooms : 5','Bathrooms: 5']},
    {"id": "3", "userId": "2","category":"housing", "title":"Small Red House","price":"1,000,000","type":"home","built":"2008","address":"34555 Nile St","city":"San Francisco","state":"CA","zipcode":"9666","seller":"Paul John","email":"pauljohn@mail.com","phone":"888-888-0000","description":"Lovely home located in the Bay Area","datePosted":"10-25-2021","username":"pauljohn3","image":"housing/image3.jpg",images:['housing/image3.jpg','housing/image8.jpg','housing/image7.jpg'],"details":['built: 2007','Type: House','Heating: Yes','Cooling: Yes','Price/sqt: 3500','Kitchen : Yes','Bedrooms : 5','Bathrooms: 5']},
    {"id": "4", "userId": "2","category":"housing", "title":"Small Red House","price":"1,000,000","type":"home","built":"2008","address":"34555 Nile St","city":"San Francisco","state":"CA","zipcode":"9666","seller":"Paul John","email":"pauljohn@mail.com","phone":"888-888-0000","description":"Lovely home located in the Bay Area","datePosted":"10-25-2021","username":"pauljohn3","image":"housing/image4.jpg",images:['housing/image4.jpg','housing/image9.jpg','housing/image10.jpg'],"details":['built: 2007','Type: House','Heating: Yes','Cooling: Yes','Price/sqt: 3500','Kitchen : Yes','Bedrooms : 5','Bathrooms: 5']},
    {"id": "5", "userId": "2","category":"housing", "title":"Simple and Clean","price":"1,000,000","type":"home","built":"2011","address":"34555 Purple Ave","city":"San Francisco","state":"CA","zipcode":"9666","seller":"Paul John","email":"pauljohn@mail.com","phone":"888-888-0000","description":"Lovely home located in the Bay Area","datePosted":"10-25-2021","username":"pauljohn3","image":"housing/image5.jpg",images:['housing/image5.jpg'],"details":['built: 2007','Type: House','Heating: Yes','Cooling: Yes','Price/sqt: 3500','Kitchen : Yes','Bedrooms : 5','Bathrooms: 5']},
    {"id": "6", "userId": "3","category":"housing", "title":"Suburban Home","price":"750,000","type":"home","built":"2015","address":"34455 Nice St","city":"San Francisco","state":"CA","zipcode":"9668","seller":"John Cena","email":"johncena@mail.com","phone":"888-888-0000","description":"Lovely home located in the Bay Area","datePosted":"10-25-2021","username":"johncena","image":"housing/image6.jpg",images:['housing/image6.jpg'],"details":['built: 2007','Type: House','Heating: Yes','Cooling: Yes','Price/sqt: 3500','Kitchen : Yes','Bedrooms : 5','Bathrooms: 5']},
]
export const personalListingsData = [];

export const jobsListingsData = [];

export const communityListingsData = [];

export const forSalesListingsData = [];

export const carsListingsData  = [
    {"id": "1", "userId": "1","category":"cars","title":"White Telsa","price":"150,000","type":"cars","address":"34555 Prove St","city":"San Francisco","state":"CA","zipcode":"9666","seller":"John Chi","email":"johnchi@mail.com","phone":"888-888-0000","description":"White Tesla","datePosted":"10-27-2021","username":"JohnChi2","image":"cars/image1.jpg",images:["cars/image1.jpg","cars/image2.jpg","cars/image3.jpg",],"details":['Built: 2019','Type: Car','Color: White','Max hp: 283','Condition: New']},
    {"id": "2", "userId": "2","category":"cars","title":"White Porsche Carerra 911","price":"500,000","type":"cars","built":"2019","address":"34555 Prove St","city":"San Francisco","state":"CA","zipcode":"9666","seller":"John Chi","email":"johnchi@mail.com","phone":"888-888-0000","description":"White Carerra 911","datePosted":"10-27-2021","username":"JohnChi2","image":"cars/image4.jpeg",images:["cars/image4.jpeg","cars/image5.jpeg","cars/image6.jpeg",],"details":['Built: 2019','Type: Car','Color: White','Max hp: 500','Condition: New']},
];